import { writeFileSync, mkdirSync } from 'node:fs';
import octicons from '@primer/octicons';
import { CURRICULUM } from '../src/data/curriculum.js';

const used = new Set([
  ...CURRICULUM.acts.flatMap(a => a.beats.flatMap(b => b.icons)),
  ...CURRICULUM.labs.flatMap(l => l.steps.flatMap(s => s.icons)),
  ...CURRICULUM.groups.flatMap(g => g.topics.flatMap(t => t.icons)),
]);

const names = [...used].sort();
const missing = names.filter(n => !octicons[n]);
if (missing.length) {
  console.error(`Unknown octicons: ${missing.join(', ')}`);
  process.exit(1);
}

const symbols = names.map(n => {
  const variant = octicons[n].heights['24'] ?? Object.values(octicons[n].heights)[0];
  const box = `0 0 ${variant.options.width} ${variant.options.height}`;
  return `<symbol id="oct-${n}" viewBox="${box}">${variant.path}</symbol>`;
}).join('');

mkdirSync(new URL('../src/icons/', import.meta.url), { recursive: true });
writeFileSync(
  new URL('../src/icons/sprite.js', import.meta.url),
  `// GENERATED by scripts/build-sprite.mjs — do not edit.\n` +
  `export const ICON_NAMES = ${JSON.stringify(names)};\n` +
  `export const SPRITE = ${JSON.stringify(`<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${symbols}</svg>`)};\n`
);

console.log(`sprite: ${names.length} icons`);
